[package]
name = "blindsheen"
version = "0.2.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
figlet-rs = "0.1.5"
image = "0.25.6"
serde_json = "1.0.140"

[build-dependencies]
winresource = "0.1.20"
